# Generated by Django 5.0.7 on 2024-07-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image1_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image2_url',
        ),
        migrations.AddField(
            model_name='event',
            name='image1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
