# Generated by Django 5.0.7 on 2024-08-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_member_is_approved_alter_member_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='photo',
        ),
    ]
