# Generated by Django 5.0.7 on 2024-08-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_remove_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='branch',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='year',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
