# Generated by Django 5.0.7 on 2024-08-04 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0005_memberrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrole',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='Member.member'),
        ),
    ]
