# Generated by Django 5.0.7 on 2024-08-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Member", "0006_memberrole_photo_url_alter_memberrole_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="bio",
        ),
    ]
